//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS_Client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.PlayerServiceSoap")]
    public interface PlayerServiceSoap {
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchPlayer", ReplyAction="*")]
        IIS_Client.ServiceReference1.SearchPlayerResponse SearchPlayer(IIS_Client.ServiceReference1.SearchPlayerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchPlayer", ReplyAction="*")]
        System.Threading.Tasks.Task<IIS_Client.ServiceReference1.SearchPlayerResponse> SearchPlayerAsync(IIS_Client.ServiceReference1.SearchPlayerRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchPlayerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchPlayer", Namespace="http://tempuri.org/", Order=0)]
        public IIS_Client.ServiceReference1.SearchPlayerRequestBody Body;
        
        public SearchPlayerRequest() {
        }
        
        public SearchPlayerRequest(IIS_Client.ServiceReference1.SearchPlayerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchPlayerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public SearchPlayerRequestBody() {
        }
        
        public SearchPlayerRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchPlayerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchPlayerResponse", Namespace="http://tempuri.org/", Order=0)]
        public IIS_Client.ServiceReference1.SearchPlayerResponseBody Body;
        
        public SearchPlayerResponse() {
        }
        
        public SearchPlayerResponse(IIS_Client.ServiceReference1.SearchPlayerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchPlayerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SearchPlayerResult;
        
        public SearchPlayerResponseBody() {
        }
        
        public SearchPlayerResponseBody(string SearchPlayerResult) {
            this.SearchPlayerResult = SearchPlayerResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PlayerServiceSoapChannel : IIS_Client.ServiceReference1.PlayerServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PlayerServiceSoapClient : System.ServiceModel.ClientBase<IIS_Client.ServiceReference1.PlayerServiceSoap>, IIS_Client.ServiceReference1.PlayerServiceSoap {
        
        public PlayerServiceSoapClient() {
        }
        
        public PlayerServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PlayerServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlayerServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlayerServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IIS_Client.ServiceReference1.SearchPlayerResponse IIS_Client.ServiceReference1.PlayerServiceSoap.SearchPlayer(IIS_Client.ServiceReference1.SearchPlayerRequest request) {
            return base.Channel.SearchPlayer(request);
        }
        
        public string SearchPlayer(string name) {
            IIS_Client.ServiceReference1.SearchPlayerRequest inValue = new IIS_Client.ServiceReference1.SearchPlayerRequest();
            inValue.Body = new IIS_Client.ServiceReference1.SearchPlayerRequestBody();
            inValue.Body.name = name;
            IIS_Client.ServiceReference1.SearchPlayerResponse retVal = ((IIS_Client.ServiceReference1.PlayerServiceSoap)(this)).SearchPlayer(inValue);
            return retVal.Body.SearchPlayerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IIS_Client.ServiceReference1.SearchPlayerResponse> IIS_Client.ServiceReference1.PlayerServiceSoap.SearchPlayerAsync(IIS_Client.ServiceReference1.SearchPlayerRequest request) {
            return base.Channel.SearchPlayerAsync(request);
        }
        
        public System.Threading.Tasks.Task<IIS_Client.ServiceReference1.SearchPlayerResponse> SearchPlayerAsync(string name) {
            IIS_Client.ServiceReference1.SearchPlayerRequest inValue = new IIS_Client.ServiceReference1.SearchPlayerRequest();
            inValue.Body = new IIS_Client.ServiceReference1.SearchPlayerRequestBody();
            inValue.Body.name = name;
            return ((IIS_Client.ServiceReference1.PlayerServiceSoap)(this)).SearchPlayerAsync(inValue);
        }
    }
}
